#!/usr/bin/osascript

# script to open preview to an individual page
# usage: openpdfpage <pdf> <page>

on run argv
do shell script "open " & quoted form of (item 1 of argv)
if (length of argv) = 2 then
tell application "Preview"
     activate
     tell application "System Events"
     	  keystroke "g" using {option down, command down}
     	  keystroke (item 2 of argv)
          keystroke return
     end tell
end tell
end if
end run